spring:
  application:
    name: CNSA

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  # H2 Database
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:book'
    username: username
    password: password

  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true


server:
  port: 8080
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 12s
    threads:
      max: 30
      min-spare: 3